port 6379
bind 0.0.0.0
protected-mode no

dir /tmp

maxmemory 96mb
maxmemory-policy allkeys-lru

save ""
appendonly no

timeout 0
tcp-keepalive 300

loglevel warning
syslog-enabled no

databases 1
lazyfree-lazy-eviction yes
lazyfree-lazy-expire yes
lazyfree-lazy-server-del yes
